name: .NET

on:
  push:
    branches: [ master, example-tests ]
  pull_request:
    branches: [ master, example-tests ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./Src/CommandLine
      run: dotnet restore
    - name: Build
      working-directory: ./Src/CommandLine
      run: dotnet build --no-restore
    - name: Export Libz3 Ubuntu
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: echo "LD_LIBRARY_PATH=${GITHUB_WORKSPACE}/Src/CommandLine/bin/Debug/net6.0/runtimes/ubuntu-x64/native" >> ${GITHUB_ENV}
    - name: Export Libz3 MacOS
      if: ${{ matrix.os == 'macOS-latest' }}
      run: echo "DYLD_LIBRARY_PATH=${GITHUB_WORKSPACE}/Src/CommandLine/bin/Debug/net6.0/runtimes/macos/native" >> ${GITHUB_ENV}
    - name: Copy to Liblibz3 MacOS
      if: ${{ matrix.os == 'macOS-latest' }}
      run: cp ${GITHUB_WORKSPACE}/Src/CommandLine/bin/Debug/net6.0/runtimes/macos/native/libz3.dylib ${GITHUB_WORKSPACE}/Src/CommandLine/bin/Debug/net6.0/runtimes/macos/native/liblibz3.dylib
    - name: Export Libz3 Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: echo "PATH=${GITHUB_WORKSPACE}/Src/CommandLine/bin/Debug/net6.0/runtimes/win-x64/native" >> ${GITHUB_ENV}
    - name: Test
      working-directory: ./Src/Tests
      run: dotnet test --no-build --verbosity normal
